export default [
  {
    img: '/ecology/1.png',
    url: 'https://mina.westake.club/',
    name: 'WeStake （2% fee）',
    tab: 1,
    id: 1,
  },
  {
    img: '/ecology/2.png',
    url: 'https://docs.minaexplorer.com/minaexplorer/staking-pool',
    name: 'MinaExplorer Staking Pool（5% fee）',
    tab: 1,
    id: 2,
  },
  {
    img: '/ecology/3.png',
    url: 'https://staketab.com/',
    name: 'Staketab pool （7% fee）',
    tab: 1,
    id: 3,
  },
  {
    img: '/ecology/4.png',
    url: 'https://zkvalidator.com/',
    name: 'ZKValidator pool （10% fee）',
    tab: 1,
    id: 4,
  },
  {
    img: '/ecology/5.png',
    url: 'https://p2p.org/',
    name: 'P2P Validator 8% fee',
    tab: 1,
    id: 5,
  },
  {
    img: '/ecology/6.png',
    url: 'https://theminapool.com/',
    name: 'TheMinaPool （5% fee）',
    tab: 1,
    id: 6,
  },
  {
    img: '/ecology/7.png',
    url:
      'https://mina.0base.vc/Mina-Staking-Pool-f03278f2fd704c4bba53c5600be5f1b4',
    name: 'Obase.vc pool （5% fee）',
    tab: 1,
    id: 7,
  },
  {
    img: '/ecology/8.png',
    url: 'https://mina.piconbello.com/',
    name: 'Piconbello pool （0% fee）',
    tab: 1,
    id: 8,
  },
  {
    img: '/ecology/9.png',
    url: 'https://stakemina.com/',
    name: 'StakeMina pool （5% fee）',
    tab: 1,
    id: 9,
  },
  {
    img: '/ecology/10.png',
    url: 'https://towerstake.com/',
    name: 'TowerStake pool 5% fee',
    tab: 1,
    id: 10,
  },
  {
    img: '/ecology/11-1.png',
    url: 'https://accomplice.co/',
    name: '',
    tab: 2,
    id: 11,
  },
  {
    img: '/ecology/11-2.png',
    url: 'http://www.alternity.capital/',
    name: '',
    tab: 2,
    id: 12,
  },
  {
    img: '/ecology/11-3.png',
    url: 'https://www.block123.com/zh-hans/nav/238154181508.htm',
    name: '',
    tab: 2,
    id: 13,
  },
  {
    img: '/ecology/11-4.png',
    url: 'http://bixincapital.com/',
    name: '',
    tab: 2,
    id: 14,
  },
  {
    img: '/ecology/11-5.png',
    url: 'https://blockchan.ge/',
    name: '',
    tab: 2,
    id: 15,
  },
  {
    img: '/ecology/11-6.png',
    url: 'https://www.block123.com/zh-hans/nav/321153675618.htm',
    name: '',
    tab: 2,
    id: 16,
  },
  {
    img: '/ecology/11-7.png',
    url: 'https://ventures.coinbase.com/',
    name: '',
    tab: 2,
    id: 17,
  },
  {
    img: '/ecology/11-8.png',
    url: 'http://www.collaborativefund.com/',
    name: '',
    tab: 2,
    id: 18,
  },
  {
    img: '/ecology/11-9.png',
    url: 'https://o1labs.org/',
    name: '',
    tab: 2,
    id: 19,
  },
  {
    img: '/ecology/11-10.png',
    url: 'https://dekrypt.capital/',
    name: '',
    tab: 2,
    id: 20,
  },
  {
    img: '/ecology/11-11.png',
    url: 'https://dacm.io/',
    name: '',
    tab: 2,
    id: 21,
  },
  {
    img: '/ecology/11-12.png',
    url: 'https://www.dcp.capital/',
    name: '',
    tab: 2,
    id: 22,
  },
  {
    img: '/ecology/11-13.png',
    url: 'http://www.romanonstartups.com/',
    name: '',
    tab: 2,
    id: 23,
  },
  {
    img: '/ecology/11-14.png',
    url: 'http://eladgil.com/',
    name: '',
    tab: 2,
    id: 24,
  },
  {
    img: '/ecology/11-15.png',
    url: 'https://electriccapital.com/',
    name: '',
    tab: 2,
    id: 25,
  },
  {
    img: '/ecology/11-16.png',
    url: 'http://evolve.vc/',
    name: '',
    tab: 2,
    id: 26,
  },
  {
    img: '/ecology/11-17.png',
    url: 'https://fenbushi.digital/',
    name: '',
    tab: 2,
    id: 27,
  },
  {
    img: '/ecology/11-19.png',
    url: 'https://www.fehrsam.xyz/',
    name: '',
    tab: 2,
    id: 28,
  },
  {
    img: '/ecology/11-19.png',
    url: 'https://www.generalcatalyst.com/',
    name: '',
    tab: 2,
    id: 29,
  },
  {
    img: '/ecology/11-20.png',
    url: 'http://hashkey.capital/',
    name: '',
    tab: 2,
    id: 30,
  },
  {
    img: '/ecology/11-21.png',
    url: 'https://imperiipartners.com/',
    name: '',
    tab: 2,
    id: 31,
  },
  {
    img: '/ecology/11-22.png',
    url: 'http://iosg.vc/',
    name: '',
    tab: 2,
    id: 32,
  },
  {
    img: '/ecology/11-23.png',
    url: 'https://www.facebook.com/JackHerrick',
    name: '',
    tab: 2,
    id: 33,
  },
  {
    img: '/ecology/11-24.png',
    url: 'http://kilowattcapital.com/',
    name: '',
    tab: 2,
    id: 34,
  },
  {
    img: '/ecology/11-25.png',
    url: 'https://kindredvc.com/',
    name: '',
    tab: 2,
    id: 35,
  },
  {
    img: '/ecology/11-26.png',
    url: 'http://ldcap.com/',
    name: '',
    tab: 2,
    id: 36,
  },
  {
    img: '/ecology/11-27.png',
    url: 'https://www.libertuscapital.com/',
    name: '',
    tab: 2,
    id: 37,
  },
  {
    img: '/ecology/11-28.png',
    url: 'http://lindajxie.com',
    name: '',
    tab: 2,
    id: 38,
  },
  {
    img: '/ecology/11-29.png',
    url: 'http://www.metastablecapital.com/',
    name: '',
    tab: 2,
    id: 39,
  },
  {
    img: '/ecology/11-30.png',
    url: 'https://multicoin.capital/',
    name: '',
    tab: 2,
    id: 40,
  },
  {
    img: '/ecology/11-31.png',
    url: 'https://startupboy.com/',
    name: '',
    tab: 2,
    id: 51,
  },
  {
    img: '/ecology/11-32.png',
    url: 'http://ngc.fund/',
    name: '',
    tab: 2,
    id: 52,
  },
  {
    img: '/ecology/11-33.png',
    url: 'http://nimacap.com/',
    name: '',
    tab: 2,
    id: 53,
  },
  {
    img: '/ecology/11-34.png',
    url: 'http://paradigm.xyz/',
    name: '',
    tab: 2,
    id: 54,
  },
  {
    img: '/ecology/11-35.png',
    url: 'http://polychain.capital',
    name: '',
    tab: 2,
    id: 55,
  },
  {
    img: '/ecology/11-36.png',
    url: 'http://scifi.vc/',
    name: '',
    tab: 2,
    id: 56,
  },
  {
    img: '/ecology/11-37.png',
    url: 'http://www.signum.capital/',
    name: '',
    tab: 2,
    id: 57,
  },
  {
    img: '/ecology/11-38.png',
    url: 'http://www.skytalecapital.com',
    name: '',
    tab: 2,
    id: 58,
  },
  {
    img: '/ecology/11-39.png',
    url: 'https://snzholding.com/',
    name: '',
    tab: 2,
    id: 59,
  },
  {
    img: '/ecology/11-40.png',
    url: 'http://www.threearrowscap.com',
    name: '',
    tab: 2,
    id: 60,
  },
  {
    img: '/ecology/11-41.png',
    url: 'http://www.ybb.io/',
    name: '',
    tab: 2,
    id: 61,
  },
];
