export default [
  {
    img: '/tool/1.png',
    zh_name: 'Mina浏览器',
    en_name: 'MinaExplorer',
    zh_title: 'MIna最常用的浏览器',
    en_title: 'The most used Mina explorer',
    url: 'https://minaexplorer.com/',
    tab: 1,
    id: 1,
  },
  {
    img: '/tool/2.png',
    zh_name: 'Hubble浏览器',
    en_name: 'Hubble Explorer',
    zh_title: '专注于质押的MINA浏览器',
    en_title: 'A Mina Explorer focused on staking',
    url: 'https://hubble.figment.io/mina/chains/mainnet',
    tab: 1,
    id: 2,
  },
  {
    img: '/tool/1-1.png',
    zh_name: 'Clorio',
    en_name: 'Clorio',
    zh_title: 'Mina协议浏览器/桌面钱包',
    en_title: 'A Mina Protocol Browser/Desktop wallet',
    url: 'https://clor.io/',
    tab: 2,
    id: 3,
  },
  {
    img: '/tool/1-2.png',
    zh_name: 'StakingPower',
    en_name: 'StakingPower',
    zh_title: 'Mina协议移动钱包',
    en_title: 'A Mina Protocol mobile wallet',
    url: '',
    tab: 2,
    id: 4,
  },
  {
    img: '/tool/2-1.png',
    zh_name: 'Mina Gas Station',
    en_name: 'Mina Gas Station',
    zh_title: '交易费和Snark估计价格',
    en_title: 'Transaction fees and Snark price estimator',
    url: 'https://fees.mina.tools/',
    tab: 3,
    id: 5,
  },
  {
    img: '/tool/2-2.png',
    zh_name: 'Mina工具',
    en_name: 'Mina Tools',
    zh_title: 'Mina协议工具网站',
    en_title: 'A website with tools for Mina Protocol',
    url: 'https://mina.tools/',
    tab: 3,
    id: 6,
  },
  {
    img: '/tool/2-3.png',
    zh_name: '验证器列表',
    en_name: 'Validators List',
    zh_title: 'main网络验证程序',
    en_title: 'Overview of validators for mainnet',
    url: 'https://mina.staketab.com/',
    tab: 3,
    id: 7,
  },
  {
    img: '/tool/3-1.png',
    zh_name: 'MinaExplorer API',
    en_name: 'MinaExplorer API',
    zh_title: '从Mina浏览器打开GraphQL API',
    en_title: 'Open GraphQL API from MinaExplorer',
    url: 'https://graphql.minaexplorer.com/',
    tab: 4,
    id: 8,
  },
  {
    img: '/tool/3-2.png',
    zh_name: 'MinaGraph API',
    en_name: 'MinaGraph API',
    zh_title: 'Mina API公共节点，从原始GraphQL API守护进程',
    en_title:
      'An alternative public GraphQL API node for Mina, exposed from the original GraphQL API of the Mina daemon',
    url: 'https://minagraph.com/',
    tab: 4,
    id: 9,
  },
  {
    img: '/tool/4-1.png',
    zh_name: 'Snark Stopper',
    en_name: 'Snark Stopper',
    zh_title: '于停止Snarkd的工具',
    en_title: 'Tool for stopping the snark',
    url: 'https://github.com/c29r3/mina-snark-stopper',
    tab: 5,
    id: 10,
  },
  {
    img: '/tool/4-2.png',
    zh_name: 'Mina节点安装',
    en_name: 'Mina Node Install',
    zh_title: 'Mina节点安装脚本',
    en_title: 'Opinionated mina node install script',
    url: 'https://github.com/jrwashburn/mina-node-install',
    tab: 5,
    id: 11,
  },
  {
    img: '/tool/4-3.png',
    zh_name: '使用Docker-compose安装',
    en_name: 'Mina Node Install with Docker-compose',
    zh_title: '多功能Mina安装组合包',
    en_title: 'All-In-One Mina install docker-compose bundle',
    url: 'https://github.com/trancemind/mina-docker-compose',
    tab: 5,
    id: 12,
  },
  {
    img: '/tool/4-4.png',
    zh_name: '性能仪表盘',
    en_name: 'Performance Dashboard',
    zh_title: '性能仪表盘',
    en_title: 'Performance Dashboard',
    url: 'https://github.com/dsrvlabs/mina-performance-dashboard',
    tab: 5,
    id: 13,
  },
  {
    img: '/tool/4-5.png',
    zh_name: 'ledger-mina-app',
    en_name: 'ledger-mina-app',
    zh_title: 'Ledger的Mina应用',
    en_title: 'Ledger’s Mina APP',
    url: 'https://github.com/jspada/ledger-app-mina',
    tab: 5,
    id: 14,
  },
  {
    img: '/tool/4-6.png',
    zh_name: 'mina-ledger-js',
    en_name: 'mina-ledger-js',
    zh_title: 'Ledger JS绑定的程序',
    en_title: 'LedgerJS bindings for ledger-mina-app',
    url: 'https://github.com/nerdvibe/mina-ledger-js',
    tab: 5,
    id: 15,
  },
  {
    img: '/tool/4-7.png',
    zh_name: 'Mina支付工具',
    en_name: 'mina-pool-payout',
    zh_title: 'jrwashburn 支付脚本',
    en_title: 'jrwashburn payout script ',
    url: 'https://github.com/jrwashburn/mina-pool-payout',
    tab: 5,
    id: 16,
  },
  {
    img: '/tool/4-8.png',
    zh_name: 'Mina浏览器支付脚本',
    en_name: 'MinaExplorer Payout Script',
    zh_title: 'Mina浏览器支付脚本',
    en_title: 'MinaExplorer Payout Script',
    url: 'https://github.com/garethtdavies/mina-payout-script',
    tab: 5,
    id: 17,
  },
  {
    img: '/tool/4-9.png',
    zh_name: 'MinaMask',
    en_name: 'MinaMask',
    zh_title: '一个用于社区创建Mina MASK化身的工具',
    en_title:
      'A tool for creating a cool Mina mask avatar, fun stuff for the Mina community',
    url: 'https://mask.minagraph.com/',
    tab: 5,
    id: 18,
  },
];
